resources:
  - ../../base
  - namespace.yaml

namespace: prod

patches:
  - patch: patches/app-deployment-patch.yaml

configMapGenerator:
  - name: app-envs
    envs:
      - envs/app.env.example

secretGenerator:
  - name: app-secrets
    files:
      - secrets/api_key.secret.example
