apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-webapp-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FaisalAl-Rayes/argocd-workshop.git
    targetRevision: HEAD
    path: gitops/components/go-webapp/overlays/dev

  destination:
    name: dev-cluster
    namespace: dev-go

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
