apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp-deployment
  labels:
    app: fastapi-webapp
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: fastapi-webapp-container
          image: falrayes/app-argocd-workshop:v1
