apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-webapp-deployment
  labels:
    app: fastapi-webapp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: fastapi-webapp-container
          image: falrayes/app-argocd-workshop:746080d3b6bce063ac992fd6416316d5a57c5dab
