apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: falrayes/go-argocd-workshop:prod-ac88801fe14b169a8655f3fb2c2dd815cd82e73e
